// <auto-generated />
using DocumentNumberApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentNumberApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211235453_FixedInitialSetup")]
    partial class FixedInitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DocumentNumberApi.Models.DocumentNumberSequence", b =>
                {
                    b.Property<string>("DocumentType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("LastSequenceNumber")
                        .HasColumnType("int");

                    b.HasKey("DocumentType", "DepartmentCode");

                    b.ToTable("DocumentSequence", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
